In [1]:
import numpy as np


np.random.uniform(low=0, high=10, size=(2))

array([7.07838405, 9.79182403])

In [28]:
any(np.array([1,2,3,4,5,6])>5)

True

In [22]:
np.clip([-51,10], -5,5)

array([-5,  5])

In [12]:
np.pi*np.random.uniform()

2.079898081170546

In [15]:
np.cos(np.pi*np.random.uniform())

0.7696374062960061

In [7]:
np.zeros_like([2,3])

array([0, 0])

In [8]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
import numpy as np

# 전체 배열 길이
total_length = 5

# A, B, C, D, E 데이터 예시 (예: 숫자)
A, B, C, D, E = 1, 2, 3, 4, 5

# 테스트 데이터를 리스트로 만듭니다.
data = [A, B, C, D, E]

# 특정 조건 함수 (예: 짝수인 경우)
def condition(x):
    return x % 2 == 0

# 조건에 맞는 데이터만 필터링합니다.
filtered_data = list(filter(condition, data))

# 할당되지 않은 나머지 부분을 0으로 채운 배열을 생성합니다.
result_array = np.zeros(total_length)

# 필터링된 데이터를 배열에 할당합니다.
result_array[:len(filtered_data)] = filtered_data

print(result_array)

[2. 4. 0. 0. 0.]


In [ ]:
np.sort

In [5]:
np.cos(3.14
    )

-0.9999987317275395

In [2]:
np.random.uniform(low=5, high=10, size=(2))

array([5.86891857, 8.07578372])

In [2]:
np.random.normal(loc=0.0, scale=1.0, size=(10, 2))

array([[-1.92859221, -2.02893264],
       [ 1.03362592,  0.34459021],
       [-0.06490318,  0.19295283],
       [ 1.06936041, -1.57349718],
       [ 0.23323946,  1.48691939],
       [-2.74428855,  1.14932602],
       [ 0.0312515 , -1.8098265 ],
       [-1.15893796,  0.46439636],
       [ 0.47813967, -0.05454096],
       [-0.81224111, -0.37211044]])

In [ ]:
np.random.normal(loc=0.0, scale=1.0, size=(10, 2))

In [14]:
a = np.array([1,2,3,4,5,6,7])


np.count_nonzero(a>4)


3

In [23]:
a[:-1]


array([1, 2, 3, 4, 5, 6])

In [24]:
a[-1]

7

In [17]:
np.rmse(1,2)

AxisError: axis 2 is out of bounds for array of dimension 0